
function PGLogin() {
    window.location.href = "../index-adm.html";
}

function PGHome() {
    window.location.href = "home-adm.html";
}

function PGUsuario() {
    window.location.href = "usuario-adm.html";
}

function PGReservas() {
    window.location.href = "reservas-adm.html";
}

function PGConfiguracoes() {
    window.location.href = "configura-adm.html";
}

function PGHomeAnimada() {
    window.location.href = "animacao3.html";
}
function excluir() {
    window.location.href = "excluir.html";
}
function abrirCatalogo() {
    document.getElementById("catalogoAdd").classList.remove("hidden");
}

function fecharCatalogo() {
    document.getElementById("catalogoAdd").classList.add("hidden");
}
