
function PGLogin() {
    window.location.href = "../index-usuario.html";
}

function PGHome() {
    window.location.href = "./home.html";
}

function PGUsuario() {
    window.location.href = "./usuario.html";
}

function PGReservas() {
    window.location.href = "./reservas.html";
}

function PGConfiguracoes() {
    window.location.href = "./configura.html";
}

function PGHomeAnimada() {
    window.location.href = "./animacao.html";
}
